version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=anotai
      - MONGO_INITDB_ROOT_USERNAME=anotai
      - MONGO_INITDB_ROOT_PASSWORD=anotai
    ports:
      - "27017:27017"
